<SplashScreen>:

    name: "splash"

    MDBoxLayout:

        orientation: "vertical"

        spacing: "20dp"

        padding: "32dp"

        md_bg_color:
            app.theme_cls.backgroundColor

        MDWidget:

        MDLabel:

            text: "AUTH APP"

            halign: "center"

            font_style: "Display"

            bold: True

        MDLabel:

            text: "Autenticador Offline"

            halign: "center"

            role: "medium"

        MDWidget: